(function() {
  const DOMAIN = 'aqhuku@ariel-networks.com';

  ahConst = {
    DOMAIN: DOMAIN,
    XULNS: 'http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul',
    prefs: {
      SERVER_URL: 'server_url',
      USER_ID: 'user_id',
      AQUA_NAVI: 'aqua_navi',
      LAST_AQUA_NAVI_JSON: 'last_aqua_navi_json',
      SHORTCUTS: 'shortcuts'
    },

    keyNames: {
      "VK_CANCEL" : "control + break",
      "VK_HELP" : "help",
      "VK_BACK_SPACE" : "バックスペース",
      "VK_TAB" : "タブ",
      "VK_CLEAR" : "clear",
      "VK_RETURN" : "リターン",
      "VK_ENTER" : "エンター",
      "VK_SHIFT" : "shift",
      "VK_CONTROL" : "control",
      "VK_ALT" : "alt",
      "VK_PAUSE" : "pause",
      "VK_CAPS_LOCK" : "CapsLock",
      "VK_ESCAPE" : "esc",
      "VK_SPACE" : "スペース",
      "VK_PAGE_UP" : "page up",
      "VK_PAGE_DOWN" : "page down",
      "VK_END" : "end",
      "VK_HOME" : "home",
      "VK_LEFT" : "←",
      "VK_UP" : "↑",
      "VK_RIGHT" : "→",
      "VK_DOWN" : "↓",
      "VK_PRINTSCREEN" : "プリントスクリーン",
      "VK_INSERT" : "insert",
      "VK_DELETE" : "delete",
      "VK_0" : "0",
      "VK_1" : "1",
      "VK_2" : "2",
      "VK_3" : "3",
      "VK_4" : "4",
      "VK_5" : "5",
      "VK_6" : "6",
      "VK_7" : "7",
      "VK_8" : "8",
      "VK_9" : "9",
      "VK_SEMICOLON" : ";",
      "VK_EQUALS" : "=",
      "VK_A" : "A",
      "VK_B" : "B",
      "VK_C" : "C",
      "VK_D" : "D",
      "VK_E" : "E",
      "VK_F" : "F",
      "VK_G" : "G",
      "VK_H" : "H",
      "VK_I" : "I",
      "VK_J" : "J",
      "VK_K" : "K",
      "VK_L" : "L",
      "VK_M" : "M",
      "VK_N" : "N",
      "VK_O" : "O",
      "VK_P" : "P",
      "VK_Q" : "Q",
      "VK_R" : "R",
      "VK_S" : "S",
      "VK_T" : "T",
      "VK_U" : "U",
      "VK_V" : "V",
      "VK_W" : "W",
      "VK_X" : "X",
      "VK_Y" : "Y",
      "VK_Z" : "Z",
      "VK_CONTEXT_MENU" : "メニュー",
      "VK_NUMPAD0" : "テンキー 0",
      "VK_NUMPAD1" : "テンキー 1",
      "VK_NUMPAD2" : "テンキー 2",
      "VK_NUMPAD3" : "テンキー 3",
      "VK_NUMPAD4" : "テンキー 4",
      "VK_NUMPAD5" : "テンキー 5",
      "VK_NUMPAD6" : "テンキー 6",
      "VK_NUMPAD7" : "テンキー 7",
      "VK_NUMPAD8" : "テンキー 8",
      "VK_NUMPAD9" : "テンキー 9",
      "VK_MULTIPLY" : "テンキー *",
      "VK_ADD" : "テンキー +",
      "VK_SEPARATOR" : "separator",
      "VK_SUBTRACT" : "テンキー -",
      "VK_DECIMAL" : "テンキー .",
      "VK_DIVIDE" : "テンキー /",
      "VK_F1" : "F1",
      "VK_F2" : "F2",
      "VK_F3" : "F3",
      "VK_F4" : "F4",
      "VK_F5" : "F5",
      "VK_F6" : "F6",
      "VK_F7" : "F7",
      "VK_F8" : "F8",
      "VK_F9" : "F9",
      "VK_F10" : "F10",
      "VK_F11" : "F11",
      "VK_F12" : "F12",
      "VK_F13" : "F13",
      "VK_F14" : "F14",
      "VK_F15" : "F15",
      "VK_F16" : "F16",
      "VK_F17" : "F17",
      "VK_F18" : "F18",
      "VK_F19" : "F19",
      "VK_F20" : "F20",
      "VK_F21" : "F21",
      "VK_F22" : "F22",
      "VK_F23" : "F23",
      "VK_F24" : "F24",
      "VK_NUM_LOCK" : "num lock",
      "VK_SCROLL_LOCK" : "scroll lock",
      "VK_COMMA" : ",",
      "VK_PERIOD" : ".",
      "VK_SLASH" : "/",
      "VK_BACK_QUOTE" : "`",
      "VK_OPEN_BRACKET" : "[",
      "VK_BACK_SLASH" : "\\",
      "VK_CLOSE_BRACKET" : "]",
      "VK_QUOTE" : "\' か \"",
      "VK_META" : "meta"
    }
  };
})();
